# Dependencies
markdown:     rdiscount
pygments:     true

# Permalinks
permalink:    pretty

# Server
# auto:          true
# source:       ./docs
# destination:  ./_gh_pages
url:  http://acmetech.github.com/todc-bootstrap-3
root: /todc-bootstrap-3
# server_port:  9002
